Disable old Plantuml plugin due to issues with site generation with newer java versions
Error:  Failed to execute goal com.github.jeluard:plantuml-maven-plugin:7954:generate (generate-plantuml-diagrams) on project jaxb2-maven-plugin: Execution generate-plantuml-diagrams of goal com.github.jeluard:plantuml-maven-plugin:7954:generate failed: An API incompatibility was encountered while executing com.github.jeluard:plantuml-maven-plugin:7954:generate: java.lang.IllegalAccessError: class net.sourceforge.plantuml.png.PngIOMetadata (in unnamed module @0xf882465) cannot access class com.sun.imageio.plugins.png.PNGMetadata (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.png to unnamed module @0xf882465